NUMERICAL_QUESTIONS = {
    "Historical Dates": [
        {"question": "In which year did World War II end?", "answer": 1945},
        {"question": "In which year was the United States Declaration of Independence signed?", "answer": 1776},
        {"question": "In which year did the Berlin Wall fall?", "answer": 1989},
        {"question": "In which year did Christopher Columbus first reach the Americas?", "answer": 1492},
        {"question": "In which year did the French Revolution begin?", "answer": 1789},
        {"question": "In which year did the Roman Empire fall (Western)?", "answer": 476},
        {"question": "In which year was the Magna Carta signed?", "answer": 1215},
        {"question": "In which year did Napoleon Bonaparte die?", "answer": 1821},
        {"question": "In which year did Charles IV, Holy Roman Emperor die?", "answer": 1378},
        {"question": "In which year was the printing press invented by Gutenberg?", "answer": 1440},
    ],
    "Geography & Numbers": [
        {"question": "How many continents are there on Earth?", "answer": 7},
        {"question": "What is the approximate height of Mount Everest in meters?", "answer": 8849},
        {"question": "How many countries are there in Africa?", "answer": 54},
        {"question": "What is the approximate population of Tokyo in millions?", "answer": 14},
        {"question": "How many time zones does Russia span?", "answer": 11},
        {"question": "What is the deepest point of the ocean in meters (Mariana Trench)?", "answer": 11034},
        {"question": "How many states are there in the United States?", "answer": 50},
        {"question": "What is the approximate length of the Great Wall of China in kilometers?", "answer": 21196},
    ],
    "Science & Nature": [
        {"question": "What is the atomic number of carbon?", "answer": 6},
        {"question": "How many bones are there in an adult human body?", "answer": 206},
        {"question": "At what temperature does water boil in Celsius?", "answer": 100},
        {"question": "How many chambers does a human heart have?", "answer": 4},
        {"question": "What is the speed of light in kilometers per second (rounded)?", "answer": 300000},
        {"question": "How many planets are in our solar system?", "answer": 8},
        {"question": "What is the approximate age of Earth in billion years?", "answer": 4},
        {"question": "How many minutes are there in a full day?", "answer": 1440},
    ],
    "Mathematics": [
        {"question": "What is the value of Pi rounded to 2 decimal places (as integer, e.g., 314 for 3.14)?", "answer": 314},
        {"question": "How many degrees are in a circle?", "answer": 360},
        {"question": "What is 12 factorial (12!)?", "answer": 479001600},
        {"question": "What is the square root of 144?", "answer": 12},
        {"question": "How many sides does a dodecagon have?", "answer": 12},
        {"question": "What is 2 to the power of 10?", "answer": 1024},
    ]
}
